# 배열의 생성 및 조작

In [2]:
import numpy as np

# 1. np.array([값들]) - 기본배열 생성

In [3]:
list1 = [1, 2, 3]
arr1 = np.array(list1)

# 초기화할 값을 지정하여 배열 생성
arr2 = np.array([1, 2, 3])

print(arr1)
print(arr2)

[1 2 3]
[1 2 3]


# 2. 수의 순차적인 증감을 이용하여 배열 생성
## np.arange([start], stop, [step])
- start: 시작 값(생략 가능, 기본값 0)
- stop: 끝 값 (필수)
- step: 증감 값 (생략 가능, 기본값 1)

In [4]:
arr3 = np.arange(10)
# arr3 = np.arange(0, 10, 1)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr4 = np.arange(1, 10)
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr5 = np.arange(1, 10 , 2)
# [1, 3, 5, 7, 9]
arr6 = np.arange(10, 1 , -1)
# [10, 9, 8, 7, 6, 5, 4, 3, 2]
arr7 = np.arange(10, 1 , -2)
# [10, 8, 6, 4, 2]

print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]
[10  8  6  4  2]


# 3. np.zeros() - 0으로 초기화된 배열 생성

In [5]:
# 1차원 배열
# np.zeros(개수)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# 2차원 배열
# np.zeros((행, 열))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 3차원 배열
# np.zeros((층, 행, 열))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 4. np.ones() - 1로 초기화된 배열 생성

In [8]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

# 5. np.random.rand() - 랜덤값 배열 생성
- 0 이상 ~ 1 미만 사이의 무작위 수로 배열 생성

In [9]:
np.random.rand(2, 3)

array([[0.18191266, 0.01177118, 0.31593612],
       [0.99540798, 0.86924705, 0.24801066]])

# 6. np.empty() - 초기화 되지 않는 배열(빠름)

In [10]:
np.empty(5)

array([0., 0., 0., 0., 0.])

## 7. np.random.rand() - 랜덤값 배열

np.random 모듈은 파이썬 내장 random 함수의 기능을 확장하여 다양한 종류의 확률분포로부터 랜덤값을 생성할 수 있음

In [11]:
np.random.rand(2, 3)

array([[0.18895125, 0.83015505, 0.82590547],
       [0.46025605, 0.13281288, 0.77270871]])

## 8. reshape() - 배열 차원 변형

In [ ]:
arr2 = np.arange(16)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
# 1차원을 2차원으로 변형
arr2.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
# 1차원을 3차원으로 변형
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## 배열 속성 확인 및 타입 변환
- shape: 각 차원의 크기
- dtype: 데이터 타입
- astype(): 데이터 타입 변환

In [15]:
arr2.shape

(16,)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

## 배열의 저장과 불러오기

### 배열 저장하기 - np.save()
- np.save('파일명', 배열명): .npy 형식으로 저장
- np.savez('파일명', 배열1, 배열2, ...): 여러 배열을 .npz 형식으로 저장
- np.savetxt('파일명', 배열1, 배열2, delimiter): 텍스트 파일로 저장

In [19]:
# 배열 생성밒 변환
# 메서드 체이닝
# - 모듈.함수().메서드()
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# 배열 저장하기
np.save('array', arr)

### 배열 불러오기 - np.load()
- np.load('파일명'): 배열 불러오기

In [23]:
load_arr = np.load('array.npy')
print(load_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
### 배열의 압축된 형식 - npz형식
- np.savez('파일명', 배열1, 배열2, ...): 여러 배열을 .npz형식으로 저장
- np.savez_compressed('파일명', )

#### 1. np.savez() - 압축된 npy 파일 생성

In [28]:
# 여러 배열 생성
arr1 = np.arange(10)
arr2 = np.arange(20).reshape(4, 5)
arr3 = np.random.rand(3, 3)

In [29]:
# 여러 배열을 하나의 파일로 
np.savez('multiple_arrays', first_array=arr1, second_array=arr2, third_array=arr3)

# 또는 이름 없이 저장
np.savez('arrays_no_name', arr1, arr2, arr3)

#### 2. npz 파일 불러오기 - np.load()

In [30]:
# npz 파일 불러오기
loaded_data = np.load('multiple_arrays.npz')

In [31]:
# 저장된 배열 이름 확인
print(loaded_data)

NpzFile 'multiple_arrays.npz' with keys: first_array, second_array, third_array


In [32]:
# 저장된 배열 이름 확인
# ['first_array', 'second_array', 'third_array']
print('117:',loaded_data.files)

117: ['first_array', 'second_array', 'third_array']


In [33]:
# 개별 배열 접근
print(loaded_data['first_array'])
print(loaded_data['second_array'])
print(loaded_data['third_array'])

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.07769105 0.65531761 0.61172503]
 [0.52882452 0.90664802 0.72161455]
 [0.75984041 0.8163742  0.26276252]]


In [34]:
# 또는 변수로 할당
arr1_loaded = loaded_data['first_array']
arr2_loaded = loaded_data['second_array']
arr3_loaded = loaded_data['third_array']

In [35]:
# 사용 후 파일 닫기
loaded_data.close()

#### 3. 압축 저장 - np.savez_compressed()

In [36]:
# 압축하여 저장(파일 크기 절약)
np.savez_compressed('compressed_arrays', data1=arr1, data2=arr2, data3=arr3)