In [ ]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
print(arr)

[1 2 3 4]


In [ ]:
## 벡터화 연산(Vectorized Operations)
print(arr + 2)

[3 4 5 6]


In [3]:
print(arr * 2)

[2 4 6 8]


In [4]:
# 리스트
list = [1, 2, 3, 4]
print(list)

[1, 2, 3, 4]


In [5]:
print(list + 2)

TypeError: can only concatenate list (not "int") to list

In [6]:
print(list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
arr1 = np.arange(5, 9)
print(arr)
print(arr1)

[1 2 3 4]
[5 6 7 8]


In [9]:
print(arr + arr1)

[ 6  8 10 12]


In [10]:
print(arr * arr1)

[ 5 12 21 32]


In [11]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [13]:
print(list + list1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [14]:
print(list * list1)

TypeError: can't multiply sequence by non-int of type 'list'