In [1]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
print(arr)

[1 2 3 4]


In [2]:
## 벡터화 연산(Vectorized Operations)
print(arr + 2)

[3 4 5 6]


In [3]:
print(arr * 2)

[2 4 6 8]


In [4]:
# 리스트
list = [1, 2, 3, 4]
print(list)

[1, 2, 3, 4]


In [5]:
print(list + 2)

TypeError: can only concatenate list (not "int") to list

In [6]:
print(list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [7]:
arr1 = np.arange(5, 9)
print(arr)
print(arr1)

[1 2 3 4]
[5 6 7 8]


In [8]:
print(arr + arr1)

[ 6  8 10 12]


In [9]:
print(arr * arr1)

[ 5 12 21 32]


In [10]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [11]:
print(list + list1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [12]:
print(list * list1)

TypeError: can't multiply sequence by non-int of type 'list'

## 주요 산술 연산 함수
### 수학 함수들

In [19]:
# 제곱
print(np.square(arr))  # array([ 1,  4,  9, 16])

# 제곱근(루트)
print(np.sqrt(arr))    # array([1.        , 1.41421356, 1.73205081, 2.        ])

# exp(지수승)
print(np.exp(arr))     # array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# log
print(np.log(arr))     # array([0.        , 0.69314718, 1.09861229, 1.38629436])

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


### 배열 연산 함수들

In [22]:
# 더하기
print(np.add(arr, arr1))  # arr + arr1과 동일. array([ 6,  8, 10, 12])
print(arr + arr1)

# 합계
print(np.sum(arr))        # 10

# 누적합
print(np.cumsum(arr))     # array([ 1,  3,  6, 10])

[2 4 6 8]
[2 4 6 8]
10
[ 1  3  6 10]


### 통계 함수들

In [ ]:
# 평균
print(np.mean(arr))     # 2.5

# 편차
print(np.var(arr))      # 1.25

# 표준편차(Standard Deviation)
# 표준편차
print(np.std(arr))      # 1.118033988749895

# 최솟값
print(np.min(arr))      # 1

# 최댓값
print(np.max(arr))      # 4

# 최솟값의 인덱스
print(np.argmin(arr))   # 0

# 최댓값의 인덱스
print(np.argmax(arr))   # 3

2.5
1.25
1.118033988749895
1
4
0
3


## 배열의 변형(Transformation)
### 1. 축 변환: 배열.transpose()

In [ ]:
# 2차원 배열 생성
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [26]:
# 2차원 배열의 축
# (2, 5) -> (5, 2): 2행 5열이 5행 2열로 변경
print(arr.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
# 3차원 배열 생성
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
# 3차원 배열의 축 변환
# (0, 1, 2) -> (1, 0, 2)
# 1: 1번 축에있던 '행'을 새로운 배열의 0번 축(면)으로
# 0: 0번 축에있던 '면'을 새로운 배열의 1번 축(행)으로
# 3: 3번 축에있던 '열'은 변함 없이 그대로 2번 축(열)로
print(arr3d.transpose(1, 0, 2))

[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


## 고급 연산 기법
### 브로드캐스팅?
- shape()이 다른 다차원배열 또는 스칼라 값 사이에서 연산이 가능

In [29]:
# 2차원 배열과 1차원 배열의 연산
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
# 축 지정 연산
# 열 방향 합계 (axis=0)
print(np.sum(arr_2d, axis=0))

# 행 방향 합계 (axis=1)
print(np.sum(arr_2d, axis=1))

In [35]:
# 조건에 따른 연산
# 배열 생성
arr = np.array([1, -2, 3, -4, 5])

# 절댓값: 양수화
print(np.abs(arr))

# 조건부 연산: np.where(조건식, 참, 거짓)
result = np.where(arr > 0, arr, 0)
print(result)

[1 2 3 4 5]
[1 0 3 0 5]


## 실무 활용 예시
### 정규화(Normalization)

In [ ]:
# 배열 생성
data = np.array([10, 20, 30, 40, 50])

# min-max 정규화
'''
([10, 20, 30, 40, 50] - 10) / (50 - 10)
([10, 20, 30, 40, 50] - 10) / 40
[0, 10, 20, 30, 40]  / 40
[0.   0.25 0.5  0.75 1.  ]

'''
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [39]:
# z-score 정규화
z_score = (data - np.mean(data)) / np.std(data)
print(z_score)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
### 배열 생성
prices = np.array([100, 102, 98, 105, 103, 99, 101])

# 3일 이동평균 함수 생성
# np.convolve(배열, 필터, mode)
# np.ones(window)/window
# np.ones(3)/3
# [1., 1., 1.]/3
# [1/3, 1/3, 1/3]
# [0.33333333 0.33333333 0.33333333]
filter_var = np.ones(3)/3
print(filter_var)
'''
[100, 102, 98, 105, 103, 99, 101]
[1/3, 1/3, 1/3]
100 * 1/3 + 102 * 1/3 + 98 * 1/3
(100 + 102 + 98) * 1/3
300.0 * 1/3
100.0

[100, 102, 98, 105, 103, 99, 101]
102 * 1/3 + 98 * 1/3 + 105 * 1/3
(102 + 98 + 105) * 1/3
305 * 1/3
101.66666667
'''
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

# 함수 호출
ma_3 = moving_average(prices, 3)
print(ma_3)

[0.33333333 0.33333333 0.33333333]
[100.         101.66666667 102.         102.33333333 101.        ]
