# 데이터 복제

In [16]:
import numpy as np
import copy

In [ ]:
# 넘파이(NumPy) 2차원 배열 생성
arr_org = np.array([[1, 2], [3, 4]])
print(arr_org)

In [4]:
# 넘파이 자체 copy() 메서드 사용
arr_copy = arr_org.copy()
ref_copy = arr_org

print(arr_copy)
print(ref_copy)

[[ 1  2]
 [ 3 50]]
[[ 1  2]
 [ 3 50]]


In [3]:
# 복사본을 수정해도 원본은 안전합니다!
# 데이터 수정
# 깊은 복사
arr_copy[0, 0] = 99
# 참조 복사
ref_copy[1, 1] = 50

# 출력
print(arr_org)
print(arr_copy)
print(ref_copy)

[[ 1  2]
 [ 3 50]]
[[99  2]
 [ 3  4]]
[[ 1  2]
 [ 3 50]]


## 2. 딕셔너리(Dictionary)의 복제 (★주의 필요)

In [13]:
# 2차원 구조의 중첩 딕셔너리
dict_org = {'group1': {'name': '김철수', 'age': 25}}

print(dict_org)

{'group1': {'name': '김철수', 'age': 25}}


In [17]:

# 깊은 복사
dict_copy = copy.deepcopy(dict_org)

# 얕은 복사
# 딕셔너리 자체 copy() 사용
dict_ref_copy = dict_org.copy()

# 데이터 수정
dict_copy['group1']['age'] = 30
dict_ref_copy['group1']['name'] = '한오리'

In [18]:
# 출력
print(dict_org)
print(dict_copy)
print(dict_ref_copy)

{'group1': {'name': '한오리', 'age': 25}}
{'group1': {'name': '김철수', 'age': 30}}
{'group1': {'name': '한오리', 'age': 25}}
